- name: practicing vairables
  hosts: web
  connection: ssh
  vars:
    NAME: "Naveen"
    AGE: "27"
    COURSE: "DevOps"
  tasks:
  - name: Getting details
    ansible.builtin.debug:
      msg: "My Name is {{NAME}} age is {{AGE}} learning {{DEVOPS}} Course"