- name: installing packages
  hosts: web
  connection: ssh
  become: yes
  tasks:
  - name: install packages through loops
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{ite.state}}"
    loop:
    - {name: tree , state: absent}
    - {name: nginx , state: absent}
    - {name: nodejs , state: absent}
    - {name: postfix , state: present}