- name: Creating directory /app
  hosts: web
  connection: ssh
  become: yes
  tasks:
  - name: checking dir exist or not
    ansible.builtin.stat:
      path: /root/app
    register: output
  - name: print exit status
    ansible.builtin.debug:
      msg: "{{output.stat.exists}}"
    when: output.stat.exists != true
  - name: "Creating  /app"
    ansible.builtin.command: mkdir /root/app/
  - name: "Print message"
    ansible.builtin.debug:
      msg: "Created /app directory"



