- name: To check user exists or not
  hosts: web
  connection: ssh
  tasks:
  - name: running command
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
  - name: print exit status
    ansible.builtin.debug:
      msg: "Output is: {{output.rc}}"
    when: output.rc != 0
  - name: creating user roboshop
    become: yes
    ansible.builtin.user:
      name: roboshop
      password: 12345
      state: present
      