- name: To check user exists or not
  hosts: web
  connection: ssh
  tasks:
  - name: running command
    ansible.builtin.command: id roboshop
    register: output
  - name: print exit status
    ansible.builtin.debug:
      msg: "Output is: {{output.rc}}"